apiVersion: batch/v1
kind: Job
metadata:
  name: msa-job
spec:
  template:
    spec:
      containers:
      - name: msa-job
        image: yash5090/msa:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
